name: pymovsci
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - jupyter
  - ipykernel
  - seaborn
  - statsmodels
  - jupyter-book
  - plotly